"use client";
import { useEffect, useRef } from "react";
import { ArrowRight, Check, Star } from "lucide-react";
import { trackEvent } from "@/lib/analytics";
import { EXPEDIA_GENERAL_AFFILIATE_URL } from "@/lib/revenuePartners";
const rel = "nofollow sponsored noopener noreferrer";
function useView(name: string, type: string) { useEffect(() => trackEvent(name, { component_type: type, placement: "conversion_section", page: location.pathname, page_path: location.pathname }), [name, type]); }
export function ConversionScrollAnalytics() { const fired = useRef(new Set<number>()); useEffect(() => { const run = () => { const max = document.documentElement.scrollHeight - innerHeight; const pct = max > 0 ? scrollY / max * 100 : 100; [50, 90].forEach((d) => { if (pct >= d && !fired.current.has(d)) { fired.current.add(d); trackEvent(`scroll_${d}`, { scroll_depth: d, page_path: location.pathname }); } }); }; addEventListener("scroll", run, { passive: true }); run(); return () => removeEventListener("scroll", run); }, []); return null; }
export function QuickDealCard() { useView("deal_card_view", "quick_deal"); return <article className="rounded-3xl border border-slate-200 bg-white p-6 shadow-card"><p className="text-xs font-black uppercase tracking-[0.14em] text-ocean">Popular hotel options</p><h2 className="mt-2 text-2xl font-black text-ink">Compare The Stay Before Booking</h2><ul className="mt-4 grid gap-2 text-sm font-semibold text-slateText">{["Current hotel availability", "Location and total fees", "Cancellation and parking terms"].map((x) => <li className="flex gap-2" key={x}><Check className="h-5 w-5 text-ocean" />{x}</li>)}</ul><a className="btn btn-primary mt-6 px-5" href="#featured-stays" onClick={() => trackEvent("deal_card_click", { component_type: "QuickDealCard", placement: "conversion_section", page: location.pathname, page_path: location.pathname })}>Check Availability <ArrowRight className="h-4 w-4" /></a></article>; }
export function RecommendedPartnerCard() { useView("partner_card_view", "recommended_partner"); const click = () => { const p = { component_type: "RecommendedPartnerCard", placement: "conversion_section", page: location.pathname, partner: "expedia", page_path: location.pathname, outbound_url: EXPEDIA_GENERAL_AFFILIATE_URL }; trackEvent("partner_card_click", p); trackEvent("affiliate_click", p); }; return <article className="rounded-3xl border border-sky-200 bg-ink p-6 text-white shadow-soft"><Star className="h-7 w-7 text-gold" /><p className="mt-4 text-xs font-black uppercase tracking-[0.14em] text-sky-200">Recommended booking partner</p><h2 className="mt-2 text-2xl font-black">Expedia</h2><p className="mt-3 text-sm font-semibold leading-6 text-white/75">Compare current hotel and trip options while reviewing the complete cost of your Florida stay.</p><a className="btn mt-6 bg-white px-5 text-ink" href={EXPEDIA_GENERAL_AFFILIATE_URL} target="_blank" rel={rel} onClick={click}>View Current Deals <ArrowRight className="h-4 w-4" /></a><p className="mt-3 text-xs font-bold text-white/60">Affiliate link. We may earn a commission at no extra cost to you.</p></article>; }
