import { BadgeDollarSign, CircleCheck, CircleX, ReceiptText } from "lucide-react";
import { TrackedLink } from "@/components/TrackedLink";

const decisions: Record<string, { answer: string; cards: Array<[string, string]> }> = {
  "clearwater-beach-hotel-deals": { answer: "Pay more for beach proximity only when it changes how you will use the stay.", cards: [["Best for", "Travelers planning repeated beach access"], ["Skip if", "The room is mainly a place to sleep"], ["Hidden cost", "Check parking, resort fees, and room-view terms"]] },
  "florida-budget-hotels": { answer: "Compare the final stay total, not the room label or starting price.", cards: [["Best for", "Short stays, road trips, and airport nights"], ["Skip if", "Added transport erases the room savings"], ["Hidden cost", "Check parking, deposits, and cancellation terms"]] },
  "best-time-to-book-florida-hotels": { answer: "The useful booking window depends on flexibility, cancellation terms, destination demand, and trip dates.", cards: [["Best for", "Travelers able to compare more than once"], ["Price driver", "Dates, events, room type, and flexibility"], ["Question", "Can you rebook if the total changes?"]] },
  "florida-resorts-with-pools": { answer: "A pool is worth prioritizing when it will replace part of the activity schedule.", cards: [["Best for", "Families and resort-focused days"], ["Skip if", "Most days will be away from the property"], ["Hidden cost", "Check resort fees, access rules, and closures"]] }
};

export function HotelDecisionModule({ slug }: { slug: string }) {
  const decision = decisions[slug];
  if (!decision) return null;
  const icons = [CircleCheck, CircleX, ReceiptText];
  return <section className="mx-auto max-w-7xl px-4 pb-12 sm:px-6 lg:px-8" aria-labelledby="hotel-decision-title"><div className="rounded-lg border border-slate-200 bg-white p-6 shadow-card sm:p-8"><p className="text-sm font-black uppercase tracking-[0.14em] text-ocean">Hotel decision check</p><h2 id="hotel-decision-title" className="mt-2 text-2xl font-black text-ink">{decision.answer}</h2><div className="mt-6 grid gap-3 md:grid-cols-3">{decision.cards.map(([label, value], index) => { const Icon=icons[index]; return <article className="rounded-lg border border-slate-200 bg-sand p-4" key={label}><Icon className="h-5 w-5 text-ocean" aria-hidden="true"/><h3 className="mt-3 font-black text-ink">{label}</h3><p className="mt-1 text-sm font-semibold leading-6 text-slateText">{value}</p></article>; })}</div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><TrackedLink className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black text-ocean" eventName="related_guide_click" href="/trip-reality/is-an-oceanfront-hotel-in-clearwater-worth-it" label="Oceanfront decision guide">Oceanfront decision guide</TrackedLink><TrackedLink className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black text-ocean" eventName="related_guide_click" href="/best-time-to-book-florida-hotels" label="When to book">When to book</TrackedLink><TrackedLink className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black text-ocean" eventName="related_guide_click" href="/florida-budget-hotels" label="Budget hotel guide">Budget hotel guide</TrackedLink><TrackedLink className="rounded-lg border border-slate-200 px-4 py-3 text-sm font-black text-ocean" eventName="related_guide_click" href="/florida-resorts-with-pools" label="Pool resort guide">Pool resort guide</TrackedLink></div></div></section>;
}
