"use client";
import { useEffect,useRef,useState } from "react";
type Item={id:string;type:string;site:string;route:string;title:string;destination:string;savedAt:string;lastVisitedAt:string;liveDataKey:string;notes:string};
const KEY="fdn-my-trip-v31";
const valid=(x:unknown):x is Item=>{if(!x||typeof x!=="object")return false;const i=x as Item;return typeof i.id==="string"&&typeof i.title==="string"&&typeof i.route==="string"&&i.route.startsWith("/")&&!i.route.startsWith("//")&&!i.route.includes("..")};
const track=(name:string,p:Record<string,string>)=>{const w=window as typeof window&{dataLayer?:unknown[];gtag?:(...a:unknown[])=>void};if(w.gtag)w.gtag("event",name,p);else{w.dataLayer=w.dataLayer||[];w.dataLayer.push({event:name,...p})}};
export function MyTrip({siteName,siteId}:{siteName:string;siteId:string}){const [items,setItems]=useState<Item[]>(()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v.filter(valid):[]}catch{return[]}}),[message,setMessage]=useState(""),file=useRef<HTMLInputElement>(null);
 useEffect(()=>{track("view_my_trip",{site:siteId,route:"/my-trip"})},[siteId]);
 const save=(next:Item[])=>{setItems(next);localStorage.setItem(KEY,JSON.stringify(next))};
 const remove=(id:string)=>{const item=items.find(x=>x.id===id);save(items.filter(x=>x.id!==id));if(item)track("remove_trip_item",{site:siteId,route:item.route,item_type:item.type,destination:item.destination||""})};
 const copy=async()=>{await navigator.clipboard.writeText(items.map(x=>x.title+" - "+location.origin+x.route).join("\n"));setMessage("Trip list copied.")};
 const exportJson=()=>{const blob=new Blob([JSON.stringify({version:"V31",items},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="florida-my-trip.json";a.click();URL.revokeObjectURL(a.href);track("export_trip",{site:siteId,route:"/my-trip"})};
 const importJson=async(e:React.ChangeEvent<HTMLInputElement>)=>{try{const parsed=JSON.parse(await e.target.files![0].text()),incoming=(Array.isArray(parsed)?parsed:parsed.items).filter(valid);const merged=[...items];for(const x of incoming)if(!merged.some(y=>y.id===x.id))merged.push(x);save(merged);setMessage("Valid saved items imported.");track("import_trip",{site:siteId,route:"/my-trip"})}catch{setMessage("That file is not a valid My Trip export.")}e.target.value=""};
 return <main className="mx-auto min-h-screen max-w-5xl px-4 py-10 sm:px-6"><p className="text-sm font-bold uppercase text-[#087f8c]">Florida Deals Network</p><h1 className="mt-2 text-4xl font-black">My Trip</h1><p className="mt-3 max-w-2xl text-slate-600">These items are saved only in this browser for {siteName}. Separate network domains cannot share local storage automatically. Export and import is the privacy-safe transfer option.</p><div className="mt-6 flex flex-wrap gap-2"><button className="rounded-md bg-[#102a43] px-4 py-2 font-bold text-white" onClick={copy} disabled={!items.length}>Copy list</button><button className="rounded-md bg-[#087f8c] px-4 py-2 font-bold text-white" onClick={exportJson} disabled={!items.length}>Export JSON</button><button className="rounded-md border px-4 py-2 font-bold" onClick={()=>file.current?.click()}>Import JSON</button><button className="rounded-md border px-4 py-2 font-bold" onClick={()=>window.print()}>Print</button><button className="rounded-md border border-red-300 px-4 py-2 font-bold text-red-700" onClick={()=>{if(confirm("Clear all saved items on this site?"))save([])}} disabled={!items.length}>Clear all</button><input accept="application/json" className="hidden" onChange={importJson} ref={file} type="file"/></div>{message?<p className="mt-4 rounded-md bg-sky-50 p-3" role="status">{message}</p>:null}<section className="mt-8"><h2 className="text-2xl font-black">Saved guides and destinations</h2>{items.length?<div className="mt-4 grid gap-3">{items.map(x=><article className="rounded-lg border bg-white p-5" key={x.id}><p className="text-xs font-bold uppercase text-slate-500">{x.type.replaceAll("_"," ")}</p><h3 className="mt-1 text-lg font-black"><a className="text-[#087f8c] underline" href={x.route}>{x.title}</a></h3>{x.destination?<p className="mt-1 text-sm text-slate-600">{x.destination}</p>:null}<p className="mt-2 text-xs text-slate-500">Saved {new Date(x.savedAt).toLocaleDateString()}</p><button className="mt-3 font-bold text-red-700 underline" onClick={()=>remove(x.id)}>Remove</button></article>)}</div>:<div className="mt-4 rounded-lg border border-dashed p-8"><h3 className="font-black">Nothing saved yet</h3><p className="mt-2 text-slate-600">Use “Save to My Trip” on an eligible guide or live page.</p></div>}</section><section className="mt-8 grid gap-4 sm:grid-cols-2"><div><h2 className="text-xl font-black">Trip checklist</h2><p className="mt-2 text-sm text-slate-600">Open a saved guide to continue its local checklist.</p></div><div><h2 className="text-xl font-black">Live refresh awareness</h2><p className="mt-2 text-sm text-slate-600">Open saved live pages for current official context. This page does not claim conditions changed without a verified comparison.</p></div></section></main>}
