/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { useState } from "react";
type Props={site:string;route:string;title:string;destination?:string;pageType?:string;articleCluster?:string;image?:string;liveDataKey?:string};
type Saved={id:string;type:string;site:string;route:string;title:string;destination:string;image:string;savedAt:string;lastVisitedAt:string;liveDataKey:string;notes:string};
const KEY="fdn-my-trip-v31";
const internal=(r:string)=>r.startsWith("/")&&!r.startsWith("//")&&!r.includes("..")&&!r.includes("\\");
const track=(name:string,p:Record<string,string|boolean>)=>{const w=window as typeof window&{dataLayer?:unknown[];gtag?:(...a:unknown[])=>void};if(w.gtag)w.gtag("event",name,p);else{w.dataLayer=w.dataLayer||[];w.dataLayer.push({event:name,...p})}};
const read=():Saved[]=>{try{const v=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(v)?v.filter(x=>internal(x.route)):[]}catch{return[]}};
export function TripRetentionTools({site,route,title,destination="",pageType="trip_reality_guide",articleCluster="v30_trip_reality",image="",liveDataKey=""}:Props){
 const id=site+":"+route,[saved,setSaved]=useState(()=>read().some(x=>x.id===site+":"+route)),[rating,setRating]=useState(""),[comment,setComment]=useState(""),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);
 function toggle(){if(!internal(route))return;try{let items=read();if(saved){items=items.filter(x=>x.id!==id);track("remove_trip_item",{site,route,item_type:pageType,destination,article_cluster:articleCluster})}else{items.push({id,type:pageType,site,route,title,destination,image,savedAt:new Date().toISOString(),lastVisitedAt:new Date().toISOString(),liveDataKey,notes:""});track("save_trip_item",{site,route,item_type:pageType,destination,article_cluster:articleCluster})}localStorage.setItem(KEY,JSON.stringify(items));setSaved(!saved)}catch{alert("Saving is unavailable in this browser. Check storage permissions and try again.")}}
 async function submit(e:React.FormEvent){e.preventDefault();if(!["yes","mostly","no"].includes(rating))return;setBusy(true);try{const r=await fetch("/api/visitor-feedback",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({site,route,pageType,articleCluster,rating,comment,website:""})});if(!r.ok)throw new Error();track("visitor_feedback",{site,route,page_type:pageType,article_cluster:articleCluster,rating,has_comment:Boolean(comment.trim())});setSent(true)}catch{alert("Feedback could not be saved right now. Please try again later.")}finally{setBusy(false)}}
 return <section className="mx-auto grid max-w-7xl gap-5 px-4 pb-12 sm:px-6 lg:grid-cols-2 lg:px-8" aria-label="Trip tools"><div className="rounded-lg border border-slate-200 bg-white p-6"><p className="text-xs font-bold uppercase text-slate-600">Return to this plan</p><h2 className="mt-2 text-xl font-black">Save this guide</h2><p className="mt-2 text-sm text-slate-600">Saved only in this browser on this site. No account or cross-site tracking.</p><button className="mt-4 min-h-11 rounded-md bg-[#087f8c] px-4 font-bold text-white" onClick={toggle} type="button">{saved?"Saved - Remove":"Save to My Trip"}</button> <a className="ml-3 font-bold text-[#087f8c] underline" href="/my-trip">View My Trip</a></div><div className="rounded-lg border border-slate-200 bg-white p-6">{sent?<div role="status"><h2 className="text-xl font-black">Thanks for the feedback</h2><p className="mt-2 text-sm text-slate-600">Your response helps us improve this guide.</p></div>:<form onSubmit={submit}><fieldset><legend className="text-xl font-black">Was this page useful?</legend><div className="mt-3 flex flex-wrap gap-2">{["yes","mostly","no"].map(x=><label className="cursor-pointer rounded-md border border-slate-300 px-3 py-2 font-bold" key={x}><input className="mr-2" name="rating" onChange={()=>setRating(x)} type="radio"/>{x==="yes"?"Yes":x==="mostly"?"Mostly":"No"}</label>)}</div></fieldset>{rating?<label className="mt-4 block text-sm font-bold">What were you still trying to figure out? <span className="font-normal">(optional)</span><textarea className="mt-2 block min-h-20 w-full rounded-md border border-slate-300 p-3" maxLength={280} onChange={e=>setComment(e.target.value)} value={comment}/></label>:null}<input aria-hidden="true" className="hidden" name="website" tabIndex={-1}/><button className="mt-4 min-h-11 rounded-md bg-[#102a43] px-4 font-bold text-white disabled:opacity-50" disabled={!rating||busy} type="submit">{busy?"Sending...":"Send feedback"}</button></form>}</div></section>
}
