import { createHash,randomUUID } from "node:crypto";
import { appendFile,mkdir } from "node:fs/promises";
import path from "node:path";
import { NextRequest,NextResponse } from "next/server";
export const runtime="nodejs";
const recent=new Map<string,number[]>(),duplicates=new Map<string,number>();
const sites=new Set(["floridadealshub","flightdealsflorida","hoteldealsflorida","cruisedealsflorida","localdealsflorida"]);
const clean=(v:unknown,max=280)=>String(v||"").replace(/<[^>]*>/g," ").replace(/[\u0000-\u001f\u007f]/g," ").replace(/\s+/g," ").trim().slice(0,max);
export async function POST(request:NextRequest){try{const body=await request.json();if(clean(body.website,40))return NextResponse.json({ok:true});const site=clean(body.site,40),route=clean(body.route,180),rating=clean(body.rating,10);if(!sites.has(site)||!route.startsWith("/")||route.startsWith("//")||route.includes("..")||!["yes","mostly","no"].includes(rating))return NextResponse.json({error:"invalid_request"},{status:400});const ua=clean(request.headers.get("user-agent"),200),bucket=createHash("sha256").update(site+ua).digest("hex").slice(0,24),now=Date.now(),hits=(recent.get(bucket)||[]).filter(x=>now-x<60000);if(hits.length>=5)return NextResponse.json({error:"rate_limited"},{status:429});hits.push(now);recent.set(bucket,hits);const comment=clean(body.comment),dedupe=createHash("sha256").update(bucket+route+rating+comment).digest("hex");if((duplicates.get(dedupe)||0)>now-300000)return NextResponse.json({error:"duplicate"},{status:409});duplicates.set(dedupe,now);const spamScore=(/(https?:\/\/|www\.)/i.test(comment)?45:0)+(comment.length>250?10:0),record={feedbackId:randomUUID(),timestamp:new Date().toISOString(),site,route,pageType:clean(body.pageType,60),articleCluster:clean(body.articleCluster,80),rating,comment,sessionToken:bucket,userAgentClass:/mobile/i.test(ua)?"mobile":"desktop_or_other",referrerClass:request.headers.get("referer")?.includes(request.nextUrl.host)?"internal":"external_or_direct",consentVersion:"v31-feedback-1",moderationStatus:spamScore>=50?"rejected":"pending_private_review",spamScore};const target=process.env.VISITOR_FEEDBACK_FILE||path.join("/tmp","fdn-feedback-"+site+".jsonl");await mkdir(path.dirname(target),{recursive:true});await appendFile(target,JSON.stringify(record)+"\n",{encoding:"utf8",mode:0o600});return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"unavailable"},{status:503})}}
